<?php


 function autoload_b80ac36bcea3fa6b3e51ef257c075ea0($class)
{
    $classes = array(
        'DhlInternational\Lib\ISService_1_0_deCustom' => __DIR__ .'/ISService_1_0_deCustom.php',
        'DhlInternational\Lib\VersionCustom' => __DIR__ .'/VersionCustom.php',
        'DhlInternational\Lib\AuthentificationTypeCustom' => __DIR__ .'/AuthentificationTypeCustom.php',
        'DhlInternational\Lib\NativeAddressTypeCustom' => __DIR__ .'/NativeAddressTypeCustom.php',
        'DhlInternational\Lib\PickupAddressTypeCustom' => __DIR__ .'/PickupAddressTypeCustom.php',
        'DhlInternational\Lib\DeliveryAddressTypeCustom' => __DIR__ .'/DeliveryAddressTypeCustom.php',
        'DhlInternational\Lib\BankTypeCustom' => __DIR__ .'/BankTypeCustom.php',
        'DhlInternational\Lib\NameTypeCustom' => __DIR__ .'/NameTypeCustom.php',
        'DhlInternational\Lib\PersonCustom' => __DIR__ .'/PersonCustom.php',
        'DhlInternational\Lib\CompanyCustom' => __DIR__ .'/CompanyCustom.php',
        'DhlInternational\Lib\CommunicationTypeCustom' => __DIR__ .'/CommunicationTypeCustom.php',
        'DhlInternational\Lib\ContactTypeCustom' => __DIR__ .'/ContactTypeCustom.php',
        'DhlInternational\Lib\PackStationTypeCustom' => __DIR__ .'/PackStationTypeCustom.php',
        'DhlInternational\Lib\PostOfficeTypeCustom' => __DIR__ .'/PostOfficeTypeCustom.php',
        'DhlInternational\Lib\CustomerTypeCustom' => __DIR__ .'/CustomerTypeCustom.php',
        'DhlInternational\Lib\ErrorTypeCustom' => __DIR__ .'/ErrorTypeCustom.php',
        'DhlInternational\Lib\ZipTypeCustom' => __DIR__ .'/ZipTypeCustom.php',
        'DhlInternational\Lib\CountryTypeCustom' => __DIR__ .'/CountryTypeCustom.php',
        'DhlInternational\Lib\ShipmentNumberTypeCustom' => __DIR__ .'/ShipmentNumberTypeCustom.php',
        'DhlInternational\Lib\StatusCustom' => __DIR__ .'/StatusCustom.php',
        'DhlInternational\Lib\DimensionCustom' => __DIR__ .'/DimensionCustom.php',
        'DhlInternational\Lib\TimeFrameCustom' => __DIR__ .'/TimeFrameCustom.php',
        'DhlInternational\Lib\DeveloperAuthentificationCustom' => __DIR__ .'/DeveloperAuthentificationCustom.php',
        'DhlInternational\Lib\GetVersionResponseCustom' => __DIR__ .'/GetVersionResponseCustom.php',
        'DhlInternational\Lib\CreateShipmentTDRequestCustom' => __DIR__ .'/CreateShipmentTDRequestCustom.php',
        'DhlInternational\Lib\CreateShipmentDDRequestCustom' => __DIR__ .'/CreateShipmentDDRequestCustom.php',
        'DhlInternational\Lib\CreateShipmentResponseCustom' => __DIR__ .'/CreateShipmentResponseCustom.php',
        'DhlInternational\Lib\GetLabelTDRequestCustom' => __DIR__ .'/GetLabelTDRequestCustom.php',
        'DhlInternational\Lib\GetLabelDDRequestCustom' => __DIR__ .'/GetLabelDDRequestCustom.php',
        'DhlInternational\Lib\GetLabelResponseCustom' => __DIR__ .'/GetLabelResponseCustom.php',
        'DhlInternational\Lib\DoManifestTDRequestCustom' => __DIR__ .'/DoManifestTDRequestCustom.php',
        'DhlInternational\Lib\DoManifestDDRequestCustom' => __DIR__ .'/DoManifestDDRequestCustom.php',
        'DhlInternational\Lib\DoManifestResponseCustom' => __DIR__ .'/DoManifestResponseCustom.php',
        'DhlInternational\Lib\DeleteShipmentTDRequestCustom' => __DIR__ .'/DeleteShipmentTDRequestCustom.php',
        'DhlInternational\Lib\DeleteShipmentDDRequestCustom' => __DIR__ .'/DeleteShipmentDDRequestCustom.php',
        'DhlInternational\Lib\DeleteShipmentResponseCustom' => __DIR__ .'/DeleteShipmentResponseCustom.php',
        'DhlInternational\Lib\GetExportDocTDRequestCustom' => __DIR__ .'/GetExportDocTDRequestCustom.php',
        'DhlInternational\Lib\GetExportDocDDRequestCustom' => __DIR__ .'/GetExportDocDDRequestCustom.php',
        'DhlInternational\Lib\GetExportDocResponseCustom' => __DIR__ .'/GetExportDocResponseCustom.php',
        'DhlInternational\Lib\GetManifestDDRequestCustom' => __DIR__ .'/GetManifestDDRequestCustom.php',
        'DhlInternational\Lib\manifestDateRangeCustom' => __DIR__ .'/manifestDateRangeCustom.php',
        'DhlInternational\Lib\GetManifestDDResponseCustom' => __DIR__ .'/GetManifestDDResponseCustom.php',
        'DhlInternational\Lib\UpdateShipmentDDRequestCustom' => __DIR__ .'/UpdateShipmentDDRequestCustom.php',
        'DhlInternational\Lib\UpdateShipmentResponseCustom' => __DIR__ .'/UpdateShipmentResponseCustom.php',
        'DhlInternational\Lib\CreationStateCustom' => __DIR__ .'/CreationStateCustom.php',
        'DhlInternational\Lib\StatusinformationCustom' => __DIR__ .'/StatusinformationCustom.php',
        'DhlInternational\Lib\PieceInformationCustom' => __DIR__ .'/PieceInformationCustom.php',
        'DhlInternational\Lib\ShipmentOrderTDTypeCustom' => __DIR__ .'/ShipmentOrderTDTypeCustom.php',
        'DhlInternational\Lib\ShipmentCustom' => __DIR__ .'/ShipmentCustom.php',
        'DhlInternational\Lib\PickupCustom' => __DIR__ .'/PickupCustom.php',
        'DhlInternational\Lib\ShipmentOrderDDTypeCustom' => __DIR__ .'/ShipmentOrderDDTypeCustom.php',
        'DhlInternational\Lib\ShipperTypeCustom' => __DIR__ .'/ShipperTypeCustom.php',
        'DhlInternational\Lib\ShipperTDTypeCustom' => __DIR__ .'/ShipperTDTypeCustom.php',
        'DhlInternational\Lib\ShipperDDTypeCustom' => __DIR__ .'/ShipperDDTypeCustom.php',
        'DhlInternational\Lib\ReceiverTypeCustom' => __DIR__ .'/ReceiverTypeCustom.php',
        'DhlInternational\Lib\ReceiverTDTypeCustom' => __DIR__ .'/ReceiverTDTypeCustom.php',
        'DhlInternational\Lib\ReceiverDDTypeCustom' => __DIR__ .'/ReceiverDDTypeCustom.php',
        'DhlInternational\Lib\IdentityTypeCustom' => __DIR__ .'/IdentityTypeCustom.php',
        'DhlInternational\Lib\ShipmentDetailsTypeCustom' => __DIR__ .'/ShipmentDetailsTypeCustom.php',
        'DhlInternational\Lib\ShipmentDetailsTDTypeCustom' => __DIR__ .'/ShipmentDetailsTDTypeCustom.php',
        'DhlInternational\Lib\AccountCustom' => __DIR__ .'/AccountCustom.php',
        'DhlInternational\Lib\AccountPaidByCustom' => __DIR__ .'/AccountPaidByCustom.php',
        'DhlInternational\Lib\ShipmentDetailsDDTypeCustom' => __DIR__ .'/ShipmentDetailsDDTypeCustom.php',
        'DhlInternational\Lib\AttendanceCustom' => __DIR__ .'/AttendanceCustom.php',
        'DhlInternational\Lib\ShipmentItemTypeCustom' => __DIR__ .'/ShipmentItemTypeCustom.php',
        'DhlInternational\Lib\ShipmentItemTDTypeCustom' => __DIR__ .'/ShipmentItemTDTypeCustom.php',
        'DhlInternational\Lib\ShipmentItemDDTypeCustom' => __DIR__ .'/ShipmentItemDDTypeCustom.php',
        'DhlInternational\Lib\ShipmentServiceTDCustom' => __DIR__ .'/ShipmentServiceTDCustom.php',
        'DhlInternational\Lib\TDServiceGroupDateTimeOptionTypeCustom' => __DIR__ .'/TDServiceGroupDateTimeOptionTypeCustom.php',
        'DhlInternational\Lib\ExpressSaturdayCustom' => __DIR__ .'/ExpressSaturdayCustom.php',
        'DhlInternational\Lib\TDServiceGroupOtherTypeCustom' => __DIR__ .'/TDServiceGroupOtherTypeCustom.php',
        'DhlInternational\Lib\InsuranceCustom' => __DIR__ .'/InsuranceCustom.php',
        'DhlInternational\Lib\ShipmentServiceDDCustom' => __DIR__ .'/ShipmentServiceDDCustom.php',
        'DhlInternational\Lib\DDServiceGroupDateTimeOptionTypeCustom' => __DIR__ .'/DDServiceGroupDateTimeOptionTypeCustom.php',
        'DhlInternational\Lib\DeliveryOnTimeCustom' => __DIR__ .'/DeliveryOnTimeCustom.php',
        'DhlInternational\Lib\DDShipmentServiceGroupIdentTypeCustom' => __DIR__ .'/DDShipmentServiceGroupIdentTypeCustom.php',
        'DhlInternational\Lib\IdentCustom' => __DIR__ .'/IdentCustom.php',
        'DhlInternational\Lib\IdentExtraCustom' => __DIR__ .'/IdentExtraCustom.php',
        'DhlInternational\Lib\IdentPremiumCustom' => __DIR__ .'/IdentPremiumCustom.php',
        'DhlInternational\Lib\ContractSubmissionCustom' => __DIR__ .'/ContractSubmissionCustom.php',
        'DhlInternational\Lib\SMSAvisoCustom' => __DIR__ .'/SMSAvisoCustom.php',
        'DhlInternational\Lib\CheckMinimumAgeCustom' => __DIR__ .'/CheckMinimumAgeCustom.php',
        'DhlInternational\Lib\DDShipmentServiceGroupPickupTypeCustom' => __DIR__ .'/DDShipmentServiceGroupPickupTypeCustom.php',
        'DhlInternational\Lib\DDServiceGroupBusinessPackInternationalTypeCustom' => __DIR__ .'/DDServiceGroupBusinessPackInternationalTypeCustom.php',
        'DhlInternational\Lib\EndorsementCustom' => __DIR__ .'/EndorsementCustom.php',
        'DhlInternational\Lib\DDServiceGroupDHLPaketTypeCustom' => __DIR__ .'/DDServiceGroupDHLPaketTypeCustom.php',
        'DhlInternational\Lib\ShipmentAdvisoryCustom' => __DIR__ .'/ShipmentAdvisoryCustom.php',
        'DhlInternational\Lib\AdvisoryDataCustom' => __DIR__ .'/AdvisoryDataCustom.php',
        'DhlInternational\Lib\EndorsementServiceconfigurationCustom' => __DIR__ .'/EndorsementServiceconfigurationCustom.php',
        'DhlInternational\Lib\EndorsementServiceconfigurationTeZuCustom' => __DIR__ .'/EndorsementServiceconfigurationTeZuCustom.php',
        'DhlInternational\Lib\DDServiceGroupOtherTypeCustom' => __DIR__ .'/DDServiceGroupOtherTypeCustom.php',
        'DhlInternational\Lib\HigherInsuranceCustom' => __DIR__ .'/HigherInsuranceCustom.php',
        'DhlInternational\Lib\CODCustom' => __DIR__ .'/CODCustom.php',
        'DhlInternational\Lib\UnfreeCustom' => __DIR__ .'/UnfreeCustom.php',
        'DhlInternational\Lib\DangerousGoodsCustom' => __DIR__ .'/DangerousGoodsCustom.php',
        'DhlInternational\Lib\BulkfreightCustom' => __DIR__ .'/BulkfreightCustom.php',
        'DhlInternational\Lib\ShipmentNotificationTypeCustom' => __DIR__ .'/ShipmentNotificationTypeCustom.php',
        'DhlInternational\Lib\ExportDocumentTDTypeCustom' => __DIR__ .'/ExportDocumentTDTypeCustom.php',
        'DhlInternational\Lib\ExportDocPositionCustom' => __DIR__ .'/ExportDocPositionCustom.php',
        'DhlInternational\Lib\ExportDocumentDDTypeCustom' => __DIR__ .'/ExportDocumentDDTypeCustom.php',
        'DhlInternational\Lib\FurtherAddressesDDTypeCustom' => __DIR__ .'/FurtherAddressesDDTypeCustom.php',
        'DhlInternational\Lib\DeliveryAdressCustom' => __DIR__ .'/DeliveryAdressCustom.php',
        'DhlInternational\Lib\LabelDataCustom' => __DIR__ .'/LabelDataCustom.php',
        'DhlInternational\Lib\ExportDocDataCustom' => __DIR__ .'/ExportDocDataCustom.php',
        'DhlInternational\Lib\ManifestStateCustom' => __DIR__ .'/ManifestStateCustom.php',
        'DhlInternational\Lib\DeletionStateCustom' => __DIR__ .'/DeletionStateCustom.php',
        'DhlInternational\Lib\BookPickupRequestCustom' => __DIR__ .'/BookPickupRequestCustom.php',
        'DhlInternational\Lib\BookPickupResponseCustom' => __DIR__ .'/BookPickupResponseCustom.php',
        'DhlInternational\Lib\PickupDetailsTypeCustom' => __DIR__ .'/PickupDetailsTypeCustom.php',
        'DhlInternational\Lib\PickupOrdererTypeCustom' => __DIR__ .'/PickupOrdererTypeCustom.php',
        'DhlInternational\Lib\PickupBookingInformationTypeCustom' => __DIR__ .'/PickupBookingInformationTypeCustom.php',
        'DhlInternational\Lib\CancelPickupRequestCustom' => __DIR__ .'/CancelPickupRequestCustom.php',
        'DhlInternational\Lib\CancelPickupResponseCustom' => __DIR__ .'/CancelPickupResponseCustom.php',
        'DhlInternational\Lib\IdentityDataCustom' => __DIR__ .'/IdentityDataCustom.php',
        'DhlInternational\Lib\DrivingLicenseCustom' => __DIR__ .'/DrivingLicenseCustom.php',
        'DhlInternational\Lib\IdentityCardCustom' => __DIR__ .'/IdentityCardCustom.php',
        'DhlInternational\Lib\BankCardCustom' => __DIR__ .'/BankCardCustom.php',
        'DhlInternational\Lib\PackstationTypeCustom' => __DIR__ .'/PackstationTypeCustom.php',
        'DhlInternational\Lib\PostfilialeTypeCustom' => __DIR__ .'/PostfilialeTypeCustom.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_b80ac36bcea3fa6b3e51ef257c075ea0');

// Do nothing. The rest is just leftovers from the code generation.
{
}
