<?php


 function autoload_6e04abc55880c05774fa7a5c889af8da($class)
{
    $classes = array(
        'DhlInternational\Lib\ISService_1_0_de' => __DIR__ .'/ISService_1_0_de.php',
        'DhlInternational\Lib\Version' => __DIR__ .'/Version.php',
        'DhlInternational\Lib\AuthentificationType' => __DIR__ .'/AuthentificationType.php',
        'DhlInternational\Lib\NativeAddressType' => __DIR__ .'/NativeAddressType.php',
        'DhlInternational\Lib\PickupAddressType' => __DIR__ .'/PickupAddressType.php',
        'DhlInternational\Lib\DeliveryAddressType' => __DIR__ .'/DeliveryAddressType.php',
        'DhlInternational\Lib\BankType' => __DIR__ .'/BankType.php',
        'DhlInternational\Lib\NameType' => __DIR__ .'/NameType.php',
        'DhlInternational\Lib\Person' => __DIR__ .'/Person.php',
        'DhlInternational\Lib\Company' => __DIR__ .'/Company.php',
        'DhlInternational\Lib\CommunicationType' => __DIR__ .'/CommunicationType.php',
        'DhlInternational\Lib\ContactType' => __DIR__ .'/ContactType.php',
        'DhlInternational\Lib\PackStationType' => __DIR__ .'/PackStationType.php',
        'DhlInternational\Lib\PostOfficeType' => __DIR__ .'/PostOfficeType.php',
        'DhlInternational\Lib\CustomerType' => __DIR__ .'/CustomerType.php',
        'DhlInternational\Lib\ErrorType' => __DIR__ .'/ErrorType.php',
        'DhlInternational\Lib\ZipType' => __DIR__ .'/ZipType.php',
        'DhlInternational\Lib\CountryType' => __DIR__ .'/CountryType.php',
        'DhlInternational\Lib\ShipmentNumberType' => __DIR__ .'/ShipmentNumberType.php',
        'DhlInternational\Lib\Status' => __DIR__ .'/Status.php',
        'DhlInternational\Lib\Dimension' => __DIR__ .'/Dimension.php',
        'DhlInternational\Lib\TimeFrame' => __DIR__ .'/TimeFrame.php',
        'DhlInternational\Lib\DeveloperAuthentification' => __DIR__ .'/DeveloperAuthentification.php',
        'DhlInternational\Lib\GetVersionResponse' => __DIR__ .'/GetVersionResponse.php',
        'DhlInternational\Lib\CreateShipmentTDRequest' => __DIR__ .'/CreateShipmentTDRequest.php',
        'DhlInternational\Lib\CreateShipmentDDRequest' => __DIR__ .'/CreateShipmentDDRequest.php',
        'DhlInternational\Lib\CreateShipmentResponse' => __DIR__ .'/CreateShipmentResponse.php',
        'DhlInternational\Lib\GetLabelTDRequest' => __DIR__ .'/GetLabelTDRequest.php',
        'DhlInternational\Lib\GetLabelDDRequest' => __DIR__ .'/GetLabelDDRequest.php',
        'DhlInternational\Lib\GetLabelResponse' => __DIR__ .'/GetLabelResponse.php',
        'DhlInternational\Lib\DoManifestTDRequest' => __DIR__ .'/DoManifestTDRequest.php',
        'DhlInternational\Lib\DoManifestDDRequest' => __DIR__ .'/DoManifestDDRequest.php',
        'DhlInternational\Lib\DoManifestResponse' => __DIR__ .'/DoManifestResponse.php',
        'DhlInternational\Lib\DeleteShipmentTDRequest' => __DIR__ .'/DeleteShipmentTDRequest.php',
        'DhlInternational\Lib\DeleteShipmentDDRequest' => __DIR__ .'/DeleteShipmentDDRequest.php',
        'DhlInternational\Lib\DeleteShipmentResponse' => __DIR__ .'/DeleteShipmentResponse.php',
        'DhlInternational\Lib\GetExportDocTDRequest' => __DIR__ .'/GetExportDocTDRequest.php',
        'DhlInternational\Lib\GetExportDocDDRequest' => __DIR__ .'/GetExportDocDDRequest.php',
        'DhlInternational\Lib\GetExportDocResponse' => __DIR__ .'/GetExportDocResponse.php',
        'DhlInternational\Lib\GetManifestDDRequest' => __DIR__ .'/GetManifestDDRequest.php',
        'DhlInternational\Lib\manifestDateRange' => __DIR__ .'/manifestDateRange.php',
        'DhlInternational\Lib\GetManifestDDResponse' => __DIR__ .'/GetManifestDDResponse.php',
        'DhlInternational\Lib\UpdateShipmentDDRequest' => __DIR__ .'/UpdateShipmentDDRequest.php',
        'DhlInternational\Lib\UpdateShipmentResponse' => __DIR__ .'/UpdateShipmentResponse.php',
        'DhlInternational\Lib\CreationState' => __DIR__ .'/CreationState.php',
        'DhlInternational\Lib\Statusinformation' => __DIR__ .'/Statusinformation.php',
        'DhlInternational\Lib\PieceInformation' => __DIR__ .'/PieceInformation.php',
        'DhlInternational\Lib\ShipmentOrderTDType' => __DIR__ .'/ShipmentOrderTDType.php',
        'DhlInternational\Lib\Shipment' => __DIR__ .'/Shipment.php',
        'DhlInternational\Lib\Pickup' => __DIR__ .'/Pickup.php',
        'DhlInternational\Lib\ShipmentOrderDDType' => __DIR__ .'/ShipmentOrderDDType.php',
        'DhlInternational\Lib\ShipperType' => __DIR__ .'/ShipperType.php',
        'DhlInternational\Lib\ShipperTDType' => __DIR__ .'/ShipperTDType.php',
        'DhlInternational\Lib\ShipperDDType' => __DIR__ .'/ShipperDDType.php',
        'DhlInternational\Lib\ReceiverType' => __DIR__ .'/ReceiverType.php',
        'DhlInternational\Lib\ReceiverTDType' => __DIR__ .'/ReceiverTDType.php',
        'DhlInternational\Lib\ReceiverDDType' => __DIR__ .'/ReceiverDDType.php',
        'DhlInternational\Lib\IdentityType' => __DIR__ .'/IdentityType.php',
        'DhlInternational\Lib\ShipmentDetailsType' => __DIR__ .'/ShipmentDetailsType.php',
        'DhlInternational\Lib\ShipmentDetailsTDType' => __DIR__ .'/ShipmentDetailsTDType.php',
        'DhlInternational\Lib\Account' => __DIR__ .'/Account.php',
        'DhlInternational\Lib\AccountPaidBy' => __DIR__ .'/AccountPaidBy.php',
        'DhlInternational\Lib\ShipmentDetailsDDType' => __DIR__ .'/ShipmentDetailsDDType.php',
        'DhlInternational\Lib\Attendance' => __DIR__ .'/Attendance.php',
        'DhlInternational\Lib\ShipmentItemType' => __DIR__ .'/ShipmentItemType.php',
        'DhlInternational\Lib\ShipmentItemTDType' => __DIR__ .'/ShipmentItemTDType.php',
        'DhlInternational\Lib\ShipmentItemDDType' => __DIR__ .'/ShipmentItemDDType.php',
        'DhlInternational\Lib\ShipmentServiceTD' => __DIR__ .'/ShipmentServiceTD.php',
        'DhlInternational\Lib\TDServiceGroupDateTimeOptionType' => __DIR__ .'/TDServiceGroupDateTimeOptionType.php',
        'DhlInternational\Lib\ExpressSaturday' => __DIR__ .'/ExpressSaturday.php',
        'DhlInternational\Lib\TDServiceGroupOtherType' => __DIR__ .'/TDServiceGroupOtherType.php',
        'DhlInternational\Lib\Insurance' => __DIR__ .'/Insurance.php',
        'DhlInternational\Lib\ShipmentServiceDD' => __DIR__ .'/ShipmentServiceDD.php',
        'DhlInternational\Lib\DDServiceGroupDateTimeOptionType' => __DIR__ .'/DDServiceGroupDateTimeOptionType.php',
        'DhlInternational\Lib\DeliveryOnTime' => __DIR__ .'/DeliveryOnTime.php',
        'DhlInternational\Lib\DDShipmentServiceGroupIdentType' => __DIR__ .'/DDShipmentServiceGroupIdentType.php',
        'DhlInternational\Lib\Ident' => __DIR__ .'/Ident.php',
        'DhlInternational\Lib\IdentExtra' => __DIR__ .'/IdentExtra.php',
        'DhlInternational\Lib\IdentPremium' => __DIR__ .'/IdentPremium.php',
        'DhlInternational\Lib\ContractSubmission' => __DIR__ .'/ContractSubmission.php',
        'DhlInternational\Lib\SMSAviso' => __DIR__ .'/SMSAviso.php',
        'DhlInternational\Lib\CheckMinimumAge' => __DIR__ .'/CheckMinimumAge.php',
        'DhlInternational\Lib\DDShipmentServiceGroupPickupType' => __DIR__ .'/DDShipmentServiceGroupPickupType.php',
        'DhlInternational\Lib\DDServiceGroupBusinessPackInternationalType' => __DIR__ .'/DDServiceGroupBusinessPackInternationalType.php',
        'DhlInternational\Lib\Endorsement' => __DIR__ .'/Endorsement.php',
        'DhlInternational\Lib\DDServiceGroupDHLPaketType' => __DIR__ .'/DDServiceGroupDHLPaketType.php',
        'DhlInternational\Lib\ShipmentAdvisory' => __DIR__ .'/ShipmentAdvisory.php',
        'DhlInternational\Lib\AdvisoryData' => __DIR__ .'/AdvisoryData.php',
        'DhlInternational\Lib\EndorsementServiceconfiguration' => __DIR__ .'/EndorsementServiceconfiguration.php',
        'DhlInternational\Lib\EndorsementServiceconfigurationTeZu' => __DIR__ .'/EndorsementServiceconfigurationTeZu.php',
        'DhlInternational\Lib\DDServiceGroupOtherType' => __DIR__ .'/DDServiceGroupOtherType.php',
        'DhlInternational\Lib\HigherInsurance' => __DIR__ .'/HigherInsurance.php',
        'DhlInternational\Lib\COD' => __DIR__ .'/COD.php',
        'DhlInternational\Lib\Unfree' => __DIR__ .'/Unfree.php',
        'DhlInternational\Lib\DangerousGoods' => __DIR__ .'/DangerousGoods.php',
        'DhlInternational\Lib\Bulkfreight' => __DIR__ .'/Bulkfreight.php',
        'DhlInternational\Lib\ShipmentNotificationType' => __DIR__ .'/ShipmentNotificationType.php',
        'DhlInternational\Lib\ExportDocumentTDType' => __DIR__ .'/ExportDocumentTDType.php',
        'DhlInternational\Lib\ExportDocPosition' => __DIR__ .'/ExportDocPosition.php',
        'DhlInternational\Lib\ExportDocumentDDType' => __DIR__ .'/ExportDocumentDDType.php',
        'DhlInternational\Lib\FurtherAddressesDDType' => __DIR__ .'/FurtherAddressesDDType.php',
        'DhlInternational\Lib\DeliveryAdress' => __DIR__ .'/DeliveryAdress.php',
        'DhlInternational\Lib\LabelData' => __DIR__ .'/LabelData.php',
        'DhlInternational\Lib\ExportDocData' => __DIR__ .'/ExportDocData.php',
        'DhlInternational\Lib\ManifestState' => __DIR__ .'/ManifestState.php',
        'DhlInternational\Lib\DeletionState' => __DIR__ .'/DeletionState.php',
        'DhlInternational\Lib\BookPickupRequest' => __DIR__ .'/BookPickupRequest.php',
        'DhlInternational\Lib\BookPickupResponse' => __DIR__ .'/BookPickupResponse.php',
        'DhlInternational\Lib\PickupDetailsType' => __DIR__ .'/PickupDetailsType.php',
        'DhlInternational\Lib\PickupOrdererType' => __DIR__ .'/PickupOrdererType.php',
        'DhlInternational\Lib\PickupBookingInformationType' => __DIR__ .'/PickupBookingInformationType.php',
        'DhlInternational\Lib\CancelPickupRequest' => __DIR__ .'/CancelPickupRequest.php',
        'DhlInternational\Lib\CancelPickupResponse' => __DIR__ .'/CancelPickupResponse.php',
        'DhlInternational\Lib\IdentityData' => __DIR__ .'/IdentityData.php',
        'DhlInternational\Lib\DrivingLicense' => __DIR__ .'/DrivingLicense.php',
        'DhlInternational\Lib\IdentityCard' => __DIR__ .'/IdentityCard.php',
        'DhlInternational\Lib\BankCard' => __DIR__ .'/BankCard.php',
        'DhlInternational\Lib\PackstationType' => __DIR__ .'/PackstationType.php',
        'DhlInternational\Lib\PostfilialeType' => __DIR__ .'/PostfilialeType.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_6e04abc55880c05774fa7a5c889af8da');

// Do nothing. The rest is just leftovers from the code generation.
{
}
